version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: WASTEFOOD
      MYSQL_ROOT_PASSWORD: R@ttr4pagesPA
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pR@ttr4pagesPA"]
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  database_data:
